"""initial migration

Revision ID: f6eb80597bbf
Revises: a52786f8745d
Create Date: 2026-01-12 13:36:13.885583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6eb80597bbf'
down_revision = 'a52786f8745d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_onboardings_employee_id_employees', 'onboardings', type_='foreignkey')
    op.drop_column('onboardings', 'employee_id')
    op.drop_constraint('fk_reviews_employee_id_employees', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_reviews_employee_id_employees', 'reviews', 'employees', ['employee_id'], ['id'])
    op.add_column('onboardings', sa.Column('employee_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_onboardings_employee_id_employees', 'onboardings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
